# Generated by Django 4.2 on 2023-04-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='past',
            old_name='questions',
            new_name='question',
        ),
    ]
